# Damn Vulnerable NodeJS Application
# https://github.com/appsecco/dvna

FROM node:19.7-buster-slim
LABEL MAINTAINER "Subash SN"

WORKDIR /app

RUN npm install -g nodemon
RUN npm install express

CMD ["/bin/bash", "/app/entrypoint-dev.sh"]
